### ISSUE TITLE
Infrequent error with scikit.image.measure.compare_ssim

### ISSUE THREAD

**Issue by Wattsy2020** [Wattsy2020/repost-detector#5]
The bot occasionally gets this error 
`win_size exceeds image extent.  If the input is a multichannel (color) image, set multichannel=True` 

multichannel is set to True so it is probably some sort of edge case, possibly related to win_size? 
Source code of the message for reference https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_structural_similarity.py

**Comment by cy19980615** [comment]
> The bot occasionally gets this error
> win_size exceeds image extent.  If the input is a multichannel (color) image, set multichannel=True
> multichannel is set to True so it is probably some sort of edge case, possibly related to win_size?
> Source code of the message for reference https://github.com/scikit-image/scikit-image/blob/master/skimage/measure/_structural_similarity.py

hello，i have the same error ,my input image shape is (2,3,128,128),could you teach me how to deal with it ?
thanks

**Comment by Wattsy2020** [comment]
To be honest I wrote this two years ago and have pretty much completely forgotton it. From the look of the commit that fixed it was something do with the dimensions so maybe check they're in the right order?
